//
//  WishlistPresenter.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WishlistPresentationLogic {
    func presentFetchFromDataStoreResult(with response: WishlistModels.FetchFromDataStore.Response)
    func presentWishlistResult(with response: WishlistModels.Wishlist.Response)
}

class WishlistPresenter: WishlistPresentationLogic {
    weak var viewController: WishlistDisplayLogic?

    // MARK: Use Case - Fetch Data From DataStore

    func presentFetchFromDataStoreResult(with response: WishlistModels.FetchFromDataStore.Response) {
        let viewModel = WishlistModels.FetchFromDataStore.ViewModel(userAttribute: response.userAttribute)
        viewController?.displayFetchFromDataStoreResult(with: viewModel)
    }  

    // MARK: Use Case - Wishlist

    func presentWishlistResult(with response: WishlistModels.Wishlist.Response) {
        let viewModel = WishlistModels.Wishlist.ViewModel(containsErrors: response.containsErrors, genericErrorMessage: response.genericErrorMessage, variablePassed: response.variablePassed)
        viewController?.displayWishlistResult(with: viewModel)
    }
}
