//
//  MovieRouter.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MovieRouterInput {
    
}

protocol MovieRouterDataSource: class {
    
}

protocol MovieRouterDataDestination: class {
    
}

class MovieRouter: MovieRouterInput {
    
    weak var viewController: MovieViewController!
    weak private var dataSource: MovieRouterDataSource!
    weak var dataDestination: MovieRouterDataDestination!
    
    init(viewController: MovieViewController, dataSource: MovieRouterDataSource, dataDestination: MovieRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
