//
//  MovieConfigurator.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MovieInteractor: MovieViewControllerOutput, MovieRouterDataSource, MovieRouterDataDestination {
}

extension MoviePresenter: MovieInteractorOutput {
}

class MovieConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MovieConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MovieViewController) {
        
        let presenter = MoviePresenter()
        presenter.output = viewController
        
        let interactor = MovieInteractor()
        interactor.output = presenter
        
        let router = MovieRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
