//
//  MoviesPresenter.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic {
    func presentFetchFromDataStoreResult(with response: MoviesModels.FetchFromDataStore.Response)
    func presentMoviesResult(with response: MoviesModels.Movies.Response)
}

class MoviesPresenter: MoviesPresentationLogic {
    weak var viewController: MoviesDisplayLogic?

    // MARK: Use Case - Fetch Data From DataStore

    func presentFetchFromDataStoreResult(with response: MoviesModels.FetchFromDataStore.Response) {
        let viewModel = MoviesModels.FetchFromDataStore.ViewModel(userAttribute: response.userAttribute)
        viewController?.displayFetchFromDataStoreResult(with: viewModel)
    }  

    // MARK: Use Case - Movies

    func presentMoviesResult(with response: MoviesModels.Movies.Response) {
        let viewModel = MoviesModels.Movies.ViewModel(containsErrors: response.containsErrors, genericErrorMessage: response.genericErrorMessage, variablePassed: response.variablePassed)
        viewController?.displayMoviesResult(with: viewModel)
    }
}
