//
//  MovieInteractor.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MovieInteractorInput {
    
}

protocol MovieInteractorOutput {
    
}

protocol MovieDataSource {
    
}

protocol MovieDataDestination {
    
}

class MovieInteractor: MovieInteractorInput, MovieDataSource, MovieDataDestination {
    
    var output: MovieInteractorOutput?
    
    // MARK: Business logic
    

}
