//
//  MoviesInteractor.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesBusinessLogic {
    func fetchFromDataStore(with request: MoviesModels.FetchFromDataStore.Request)
    func Movies(with request: MoviesModels.Movies.Request)
}

protocol MoviesDataStore {
    var attribute: String? { get set }
}

class MoviesInteractor: MoviesBusinessLogic, MoviesDataStore {
    var worker: MoviesWorker?
    var presenter: MoviesPresentationLogic?

    var attribute: String?

    // MARK: Use Case - Fetch Data From DataStore

    func fetchFromDataStore(with request: MoviesModels.FetchFromDataStore.Request) {
        attribute = ""
        let response = MoviesModels.FetchFromDataStore.Response(userAttribute: attribute!)
        presenter?.presentFetchFromDataStoreResult(with: response)
    }

    // MARK: Use Case - Movies

    func Movies(with request: MoviesModels.Movies.Request) {

        var isError = false
        var variablePassed = MoviesModels.VariablePassed()

        // MARK: Empty variablePassed Check

        if request.variableToPass == nil {
            isError = true
            variablePassed.errorMessage = "Some localised empty/nil error message string."
        }

        if isError {
            let response = MoviesModels.Movies.Response(containsErrors: true, genericErrorMessage: nil, variablePassed: variablePassed)
            presenter?.presentMoviesResult(with: response)
            return
        }

        // MARK: Execute Use Case

        worker = MoviesWorker()
        worker?.Movies(completionHandler: { (isSuccessful, errorMessage) in
            if isSuccessful {
                self.attribute = request.variableToPass!

                let response = MoviesModels.Movies.Response(containsErrors: false, genericErrorMessage: nil, variablePassed: variablePassed)
                self.presenter?.presentMoviesResult(with: response)
            }
            else {
                let response = MoviesModels.Movies.Response(containsErrors: true, genericErrorMessage: errorMessage, variablePassed: variablePassed)
                self.presenter?.presentMoviesResult(with: response)
            }
        })
    }
}
