//
//  WatchedInteractor.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchedBusinessLogic {
    func fetchFromDataStore(with request: WatchedModels.FetchFromDataStore.Request)
    func Watched(with request: WatchedModels.Watched.Request)
}

protocol WatchedDataStore {
    var attribute: String? { get set }
}

class WatchedInteractor: WatchedBusinessLogic, WatchedDataStore {
    var worker: WatchedWorker?
    var presenter: WatchedPresentationLogic?

    var attribute: String?

    // MARK: Use Case - Fetch Data From DataStore

    func fetchFromDataStore(with request: WatchedModels.FetchFromDataStore.Request) {
        attribute = ""
        let response = WatchedModels.FetchFromDataStore.Response(userAttribute: attribute!)
        presenter?.presentFetchFromDataStoreResult(with: response)
    }

    // MARK: Use Case - Watched

    func Watched(with request: WatchedModels.Watched.Request) {

        var isError = false
        var variablePassed = WatchedModels.VariablePassed()

        // MARK: Empty variablePassed Check

        if request.variableToPass == nil {
            isError = true
            variablePassed.errorMessage = "Some localised empty/nil error message string."
        }

        if isError {
            let response = WatchedModels.Watched.Response(containsErrors: true, genericErrorMessage: nil, variablePassed: variablePassed)
            presenter?.presentWatchedResult(with: response)
            return
        }

        // MARK: Execute Use Case

        worker = WatchedWorker()
        worker?.Watched(completionHandler: { (isSuccessful, errorMessage) in
            if isSuccessful {
                self.attribute = request.variableToPass!

                let response = WatchedModels.Watched.Response(containsErrors: false, genericErrorMessage: nil, variablePassed: variablePassed)
                self.presenter?.presentWatchedResult(with: response)
            }
            else {
                let response = WatchedModels.Watched.Response(containsErrors: true, genericErrorMessage: errorMessage, variablePassed: variablePassed)
                self.presenter?.presentWatchedResult(with: response)
            }
        })
    }
}
