//
//  WatchedRouter.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchedRoutingLogic {
    func routeToSomewhere()
}

protocol WatchedDataPassing {
    var dataStore: WatchedDataStore? { get }
}

class WatchedRouter: NSObject, WatchedRoutingLogic, WatchedDataPassing {
    var viewController: WatchedViewController?
    var dataStore: WatchedDataStore?

    // MARK: Routing

    func routeToSomewhere() {
        routeToSomewhere(segue: nil)
    }

    func routeToSomewhere(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! WatchedViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataTo(&destinationDS, from: dataStore!)
        }
        else {
            let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SomewhereViewController") as! WatchedViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataTo(&destinationDS, from: dataStore!)
            viewController?.navigationController?.pushViewController(destinationVC, animated: true)
        }
    }

    // MARK: Data Passing

    func passDataTo(_ destinationDS: inout WatchedDataStore, from sourceDS: WatchedDataStore) {
        destinationDS.attribute = sourceDS.attribute
    }
}
