//
//  WatchedModels.swift
//  Movies
//
//  Created by Lorrayne Paraiso  on 30/10/18.
//  Copyright (c) 2018 Lorrayne Paraiso. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WatchedModels {

    // MARK: Use Cases

    enum FetchFromDataStore {
        struct Request {
        }

        struct Response {
            var userAttribute: String
        }

        struct ViewModel {
            var userAttribute: String
        }
    }  

    enum Watched {
        struct Request {
            var variableToPass: String?
        }

        struct Response {
            var containsErrors: Bool
            var genericErrorMessage: String?
            var variablePassed: VariablePassed?
        }

        struct ViewModel {
            var containsErrors: Bool
            var genericErrorMessage: String?
            var variablePassed: VariablePassed?
        }
    }

    // MARK: View Models

    struct VariablePassed {
        var errorMessage: String?
    }
}
